{% set name = "matsubplots" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfd918a823ddb95113d1469ecce041b794a212acc5117f2746922c6df6ae44e6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - python >=3.7

test:
  imports:
    - matsubplots

about:
  home: https://auneri.github.io/matsubplots
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Better subplots for matplotlib

extra:
  recipe-maintainers:
    - auneri
