{% set name = "matsubplots" %}
{% set version = "1.3.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54e611e4d15f31a073ebcc47bef437a801b33675ea7a03b8a2cc4fbd3047f58d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
  run:
    - matplotlib-base
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - matsubplots

about:
  home: https://auneri.github.io/matsubplots
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Better subplots for matplotlib

extra:
  recipe-maintainers:
    - auneri
