{% set name = "matsubplots" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de2c4a0e55af15b2f926461f8c9c435b764b762ea44d17604f15a997aee9c8e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - python >=3.7

test:
  imports:
    - matsubplots

about:
  home: https://auneri.github.io/matsubplots
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Better subplots for matplotlib

extra:
  recipe-maintainers:
    - auneri
